name: Maintainers Only
description: Internal tracking issue
title: "[Internal] "
labels: ["internal"]
assignees: ["ly-sec"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ This template is intended for maintainers only.
  - type: textarea
    id: description
    attributes:
      label: Task / Bug
    validations: